service: stock-bot

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION, "us-east-1"}
  stage: ${env:SLS_STAGE, "prod"}
  memorySize: 1024
  timeout: 120
  logRetentionInDays: 30

functions:
  stockBot:
    handler: src/lambda.handler
    events:
      - schedule:
          rate: cron(0 16 ? * MON *)
          timezone: America/Argentina/Buenos_Aires
          input:
            job: long
      - schedule:
          rate: cron(0 17 ? * MON *)
          timezone: America/Argentina/Buenos_Aires
          input:
            job: short

package:
  patterns:
    - "src/**"
    - "tickers.json"
    - "package.json"
    - "node_modules/**"
